import os
import sys

def getAssetPath(file):
    return getBundlePath('assets/' + file)

# get tmp folder path generated by Pyinstaller bundle
def getBundlePath(file):
    try:
        return os.path.join(sys._MEIPASS, file)
    except AttributeError:
        return file