import os
import sys

from PIL import ImageTk, Image


def getAsset(file):
    return ImageTk.PhotoImage(Image.open(getBundlePath('assets/' + file)))

# get tmp folder path generated by Pyinstaller bundle
def getBundlePath(file):
    try:
        return os.path.join(sys._MEIPASS, file)
    except AttributeError:
        return file

def loadAssets():
    global addIcon
    global deleteIcon
    global foundIcon
    global unfoundIcon
    global uncheckedIcon
    global favicon

    addIcon = getAsset('add.png')
    deleteIcon = getAsset('delete.png')
    foundIcon = getAsset('found.png')
    unfoundIcon = getAsset('unfound.png')
    uncheckedIcon = getAsset('unchecked.png')
    favicon = getAsset('favicon.png')
