import os
import sys

from PIL import ImageTk, Image


QUEST_ID_ENTRY_WIDTH = 7

def getAsset(file):
    return ImageTk.PhotoImage(Image.open(getBundlePath('assets/' + file)))

# get tmp folder path generated by Pyinstaller bundle
def getBundlePath(file):
    try:
        return os.path.join(sys._MEIPASS, file)
    except AttributeError:
        return file

def loadAssets():
    global favicon
    favicon = getAsset('favicon.png')

    global wowheadIcon
    wowheadIcon = getAsset('wowhead.png')

    global addIcon
    addIcon = getAsset('add.png')
    global deleteIcon
    deleteIcon = getAsset('delete.png')

    global foundIcon
    foundIcon = getAsset('found.png')
    global unfoundIcon
    unfoundIcon = getAsset('unfound.png')
    global uncheckedIcon
    uncheckedIcon = getAsset('unchecked.png')
