import tkinter as tk
from PIL import ImageTk, Image

import sys
import os

statusText = None

# get tmp folder path generated by Pyinstaller bundle
def getBundlePath(file):
    if hasattr(sys, '_MEIPASS'):
        path = os.path.join(sys._MEIPASS, file)
    else:
        path = file
    return path

def popupView(msg):
    popupWindow = tk.Tk()
    popupWindow.wm_title('Is a Sabertron up ?')
    label = tk.Label(popupWindow, text=msg, font=('Helvetica', 10))
    label.pack(side='top', fill='x', pady=10)
    B1 = tk.Button(popupWindow, text='Okay', command = popupWindow.destroy)
    B1.pack()
    popupWindow.mainloop()

def createStatusView(closeCallback, regionCallback):
    global statusText

    statusWindow = tk.Tk()
    statusWindow.wm_title('Sabertron Checker')
    statusWindow.tk.call('wm', 'iconphoto', statusWindow._w, ImageTk.PhotoImage(Image.open(getBundlePath('icon.jpg'))))

    mainFrame = tk.Frame(statusWindow, height=500, width=250)
    mainFrame.pack(fill='both', expand=True)
    mainFrame.grid_propagate(False)
    mainFrame.grid_rowconfigure(0, weight=1)
    mainFrame.grid_columnconfigure(0, weight=1)

    radioFrame = tk.Frame(mainFrame, height=500, width=250)
    radioFrame.grid(row=0, column=0)
    radioFrame.grid_propagate(False)
    radioFrame.grid_rowconfigure(0, weight=1)
    radioFrame.grid_columnconfigure(0, weight=1)

    region = None
    naRadio = tk.Radiobutton(radioFrame, text="NA", variable=region, value='na', command=lambda:regionCallback('na'))
    naRadio.grid(row=0, column=1)
    euRadio = tk.Radiobutton(radioFrame, text="EU", variable=region, value='eu', command=lambda:regionCallback('eu'))
    euRadio.grid(row=0, column=0)
    euRadio.select()

    statusText = tk.Text(mainFrame, font=('Helvetica', 10))
    statusText.grid(row=1, column=0, sticky='nsew', padx=2, pady=2)

    statusTextScrollBar = tk.Scrollbar(mainFrame, command=statusText.yview)
    statusText['yscrollcommand'] = statusTextScrollBar.set
    statusTextScrollBar.grid(row=1, column=1, sticky='nsew')

    closeButton = tk.Button(mainFrame, text='Close', command=closeCallback)
    closeButton.grid(row=2, column=0, sticky='nsew')

    return statusWindow

def addStatusMsg(msg):
    statusText.insert(tk.END, msg + '\n')