import tkinter as tk
from PIL import ImageTk, Image

import sys
import os

statusText = None

# get tmp folder path generated by Pyinstaller bundle
def getBundlePath(file):
    if hasattr(sys, '_MEIPASS'):
        path = os.path.join(sys._MEIPASS, file)
    else:
        path = file
    return path

def popupView(msg):
    popupWindow = tk.Tk()
    popupWindow.wm_title('Is a Sabertron up ?')
    label = tk.Label(popupWindow, text=msg, font=('Helvetica', 10))
    label.pack(side='top', fill='x', pady=10)
    B1 = tk.Button(popupWindow, text='Okay', command = popupWindow.destroy)
    B1.pack()
    popupWindow.mainloop()

def createStatusView(closeCallback, regionCallback, checkNowCallback):
    global statusText

    statusWindow = tk.Tk()
    statusWindow.wm_title('World Quests Checker')
    statusWindow.tk.call('wm', 'iconphoto', statusWindow._w, ImageTk.PhotoImage(Image.open(getBundlePath('icon.jpg'))))

    mainFrame = tk.Frame(statusWindow)
    mainFrame.pack(fill='both', expand=True)

    # Radio buttons

    radioFrame = tk.Frame(mainFrame)
    radioFrame.grid(row=0, column=0, sticky='we', padx=2, pady=2)
    radioFrame.grid_columnconfigure(0, weight=1)

    tk.Label(radioFrame, text="Region", anchor=tk.W).grid(row=0, column=0, sticky=tk.W)

    region = None
    naRadio = tk.Radiobutton(radioFrame, text="NA", variable=region, value='na', command=lambda:regionCallback('na'))
    naRadio.grid(row=0, column=2)
    euRadio = tk.Radiobutton(radioFrame, text="EU", variable=region, value='eu', command=lambda:regionCallback('eu'))
    euRadio.grid(row=0, column=1)
    euRadio.select()

    # Status text

    statusFrame = tk.Frame(mainFrame)
    statusFrame.grid(row=1, column=0, sticky='we', padx=2, pady=2)
    statusFrame.grid_columnconfigure(0, weight=1)

    statusText = tk.Text(statusFrame, font=('Helvetica', 10))
    statusText.grid(row=0, column=0, padx=2, pady=2)
    statusText.config(state=tk.DISABLED)

    statusTextScrollBar = tk.Scrollbar(statusFrame, command=statusText.yview)
    statusText['yscrollcommand'] = statusTextScrollBar.set
    statusTextScrollBar.grid(row=0, column=1, sticky='ns')

    # Buttons

    buttonsFrame = tk.Frame(mainFrame)
    buttonsFrame.grid(row=2, column=0, sticky='we', padx=2, pady=2)

    tk.Button(buttonsFrame, text='Check now', command=checkNowCallback).grid(row=0, column=0, padx=2, pady=2)
    tk.Button(buttonsFrame, text='Close', command=closeCallback).grid(row=0, column=1, padx=2, pady=2)

    return statusWindow

def addStatusMsg(msg):
    statusText.config(state=tk.NORMAL)
    statusText.insert(tk.END, msg + '\n')
    statusText.config(state=tk.DISABLED)