import os
import sys

HOUR_IN_SECOND = 60*60
QUEST_ID_ENTRY_WIDTH = 7


# get tmp folder path generated by Pyinstaller bundle
def getBundlePath(file):
    try:
        return os.path.join(sys._MEIPASS, file)
    except AttributeError:
        return file

